version: "3.9"
services:
  database:
    image: "postgres"
    environment:
      POSTGRES_PASSWORD: Big-Blue-Beach
      POSTGRES_DB: Creatures
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: